# 各プロジェクトに配置し利用ください。
# このファイルはサンプルです。

version: '3'
services:
  salesforce-dev:
    image: ghcr.io/Yuta-Haruna/salesforce-docker-env:latest  # 環境リポジトリの最新イメージ
    container_name: salesforce-dev
    volumes:
      - .:/workspace  # 開発者のローカルフォルダをコンテナと共有
    environment:
      - SF_CODE_COVERAGE_REQUIREMENT=75   # デフォルト値(プロジェクト毎に変更ください)
      - SF_AUTOUPDATE_DISABLE=true        # 自動更新オプションの停止
    tty: true
    stdin_open: true
